### ISSUE TITLE
Possible division by zero in crowding distance assignment

### ISSUE THREAD

**Issue by leoll2** [gsoleilhac/NSGAII.jl#2]
Hello, while inspecting your code I noticed a potential flaw in the crowding distance assignment function.
I see that you split `crowding_distance_assignement!` in two cases: one for when you have only 2 objective functions, the other for more than 2.
I assume this is an optimization to avoid a sort in the first case, which is fine and makes sense.
However, I think that you forgot to check `if pop[1].y[1] != pop[end].y[1]` and `if pop[1].y[2] != pop[end].y[2]` in the first case, which could become a source of zero division errors when the whole population shares the same fitness for at least one objective.
In the second case, instead, you perform the check (line 112) and that's good.
I think it's just an oversight, because I see no reason to assume pop[end].y[1] always different from pop[1].y[1]

PS: I also suggest to rename 'assignement' into 'assignment'

**Comment by gsoleilhac** [comment]
Hello, yes i do have some divisions by zero that yield NaNs, however if the individuals are equal on one objective, they're gonna be equal on the second also (because crowding is calculated for indivs of a same rank), so the result is the same : we have no way to tell which indivs are better. I added a condition to return immediately if that's the case, and I renamed assignement as you suggested, thank you :)
